import test from 'node:test';import assert from 'node:assert/strict';import {createCaptureSet} from '../scripts/capture-set.mjs';
const request=(page,captureId='c')=>({sessionId:'s',stepIndex:0,intent:'goal',candidates:{inspect_next:{op:'inspect_context'},inspect_previous:{op:'inspect_context'}},observation:{limited:true,snapshot:`section${page}`,refs:{[`e${page}`]:{role:'button',name:'Mark'}},objectContext:{objects:[{id:'root',headings:['Set']},{id:`o${page}`,role:'article',headings:[`Record ${page}`]}],owners:{[`e${page}`]:`o${page}`}},observationWindow:{captureId,page,pages:2,totalObjects:2,sourceLimited:false}}});
test('collect once, combine same capture, route to current target without model calls',()=>{const c=createCaptureSet();assert.equal(c.observe(request(0)).choice,'inspect_next');assert.equal(c.observe(request(1)).choice,'inspect_previous');const r=c.observe(request(0));assert.equal(r.observation.limited,false);assert.equal(r.observation.objectContext.objects.length,3);assert.equal(r.observation.captureCoverage.websiteCoverage,'unassessed');assert.equal(c.route(request(1),'o0'),'inspect_previous');assert.equal(c.observe(request(0)).observation.limited,false);});
test('changed capture invalidates retained evidence',()=>{const c=createCaptureSet();c.observe(request(0));assert.equal(c.observe(request(1,'new')).choice,'inspect_previous');});
test('source truncation or missing objects cannot become complete evidence',()=>{for(const modify of [r=>r.observation.observationWindow.sourceLimited=true,r=>r.observation.observationWindow.totalObjects=3]){const c=createCaptureSet();const a=request(0),b=request(1);modify(a);modify(b);c.observe(a);c.observe(b);assert.equal(c.observe(a).observation.limited,true);}});
test('inconsistent repeated root evidence or ref ownership remains limited',()=>{const c=createCaptureSet();c.observe(request(0));const b=request(1);b.observation.objectContext.objects[0].headings=['Other'];c.observe(b);assert.equal(c.observe(request(0)).observation.limited,true);});

test('automatic evidence collection restores its starting section only once per capture',()=>{
 const c=createCaptureSet();assert.equal(c.observe(request(1)).choice,'inspect_previous');assert.equal(c.observe(request(0)).choice,'inspect_next');assert.equal(c.observe(request(1)).observation.limited,false);assert.equal(c.observe(request(0)).observation.limited,false);
 assert.equal(c.observe(request(0,'new')).choice,'inspect_next');assert.equal(c.observe(request(1,'new')).choice,'inspect_previous');
});
