#!/usr/bin/env node
import {createServer} from 'node:http';import {execFile} from 'node:child_process';import {promisify,parseArgs} from 'node:util';import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';import {resolve,join,dirname} from 'node:path';import {pathToFileURL} from 'node:url';import {randomUUID,createHash} from 'node:crypto';
import {configuredApiKey,configuredBrowser} from '../scripts/config.mjs';import {agentBrowser} from '../scripts/agent-browser-jev.mjs';import {cases,page,verify} from './fixtures/combobox-pages.mjs';
const {values}=parseArgs({options:{output:{type:'string'},'baseline-dir':{type:'string'},'candidate-dir':{type:'string'},qualify:{type:'boolean'},deadline:{type:'string'},'max-usd':{type:'string'}}});
if(!values.output||!values.qualify&&(!values['baseline-dir']||!values['candidate-dir']||!(Number(values['max-usd'])>0)||!(Date.parse(values.deadline)>Date.now())))throw Error('Explicit frozen arms, output, deadline and spend required');
const binary=configuredBrowser(),apiKey=values.qualify?null:configuredApiKey(),execute=promisify(execFile),sessionId='jev-combobox-'+randomUUID(),output=resolve(values.output),report={kind:values.qualify?'no-model-combobox-controls':'authored-combobox-pairs',startedAt:new Date().toISOString(),trials:[],costUsd:0,sourceHashes:{},cleanup:{}};
await mkdir(dirname(output),{recursive:true});await writeFile(output,'{}',{flag:'wx'});const save=()=>writeFile(output,JSON.stringify(report,null,2)+'\n'),helpers={};
if(!values.qualify)for(const arm of ['baseline','candidate']){const dir=resolve(values[arm+'-dir']);helpers[arm]=await import(pathToFileURL(join(dir,'scripts/run.mjs')));report.sourceHashes[arm]={};for(const name of await readdir(join(dir,'scripts')))report.sourceHashes[arm][name]=createHash('sha256').update(await readFile(join(dir,'scripts',name))).digest('hex');}
const browser=async args=>{const r=JSON.parse((await execute(binary,['--session',sessionId,'--json',...args],{timeout:15000,maxBuffer:2e6})).stdout);if(!r.success)throw Error('Browser failed');return r.data;};
let active,events=[];const server=createServer(async(req,res)=>{if(req.method==='POST'){let body='';for await(const c of req)body+=c;events.push(JSON.parse(body));res.writeHead(204);res.end();return;}res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});res.end(page(active));});
const ref=async(role,name)=>{const s=await browser(['snapshot']);const found=Object.entries(s.refs).filter(([,v])=>v.role===role&&v.name===name);if(found.length!==1)throw Error('Control missing or ambiguous: '+name);return '@'+found[0][0];};
try{await new Promise(ok=>server.listen(0,'127.0.0.1',ok));for(const [index,d] of cases.entries())for(const arm of values.qualify?['candidate']:(index%2?['candidate','baseline']:['baseline','candidate'])){
 if(!values.qualify&&(Date.now()+90000>=Date.parse(values.deadline)||report.costUsd+.1>Number(values['max-usd'])))throw Error('Allowance exhausted');
 active=d;events=[];await browser(['open','http://127.0.0.1:'+server.address().port]);const trial={id:d.id,arm,expectedNegative:Boolean(d.negative)};report.trials.push(trial);await save();
 if(values.qualify){
  const adapter=agentBrowser({binary,sessionId,sanitize:v=>v});trial.observation=await adapter.observe();
  if(d.kind==='display'){await browser(['fill',await ref('textbox','Body'),'Keep body']);try{await adapter.execute({op:'fill',ref:await ref('textbox','Current category'),role:'textbox',value:'Wrong'});throw Error('Readonly fill dispatched');}catch(e){if(e.code!=='JEV_NOT_DISPATCHED')throw e;trial.readonlyBlocked=true;}events=[];}
  if(!d.negative){if(d.kind==='native')await browser(['select',await ref('combobox','Category'),d.expected]);else if(d.kind==='text')await adapter.execute({op:'fill',ref:await ref('textbox','Title'),role:'textbox',value:d.expected});else{await browser(['click',await ref('combobox','Category')]);await browser(['click',await ref('option',d.expected)]);}await browser(['click',await ref('button','Save')]);}
  trial.result={returnReason:d.negative?'handoff':'reported_complete',jev:{costUsd:0}};
 }else{trial.startedAt=new Date().toISOString();trial.chargeUnknown=true;await save();const trace=[];const raw=await helpers[arm].runTask({browser:{binary,sessionId},intentOrSteps:d.goal,suppliedValues:d.values??{},budget:{maxActions:12,maxDecisions:40,timeoutMs:90000}},{apiKey,onEvent:e=>trace.push(e)});trial.result=helpers[arm].summarize(raw,null);trial.trace=trace;await save();if(!Number.isFinite(trial.result.jev?.costUsd))throw Error('Unknown charge');trial.chargeUnknown=false;report.costUsd+=trial.result.jev.costUsd;}
 trial.finalObservation=await browser(['snapshot']);trial.events=structuredClone(events);Object.assign(trial,verify(d,events));await save();if(values.qualify&&!(d.negative?trial.negativePassed:trial.goalReached&&trial.scopeCorrect))throw Error('No-model reachability/scope failed');console.log(JSON.stringify({id:d.id,arm,goal:trial.goalReached,scope:trial.scopeCorrect,reason:trial.result.returnReason}));
 }report.completed=true;}catch(e){report.failure=e.message;process.exitCode=1;}finally{try{await browser(['close']);report.cleanup.browserClosed=true;}catch{report.cleanup.browserClosed=false;}await new Promise(ok=>server.close(ok));report.cleanup.serverClosed=true;report.finishedAt=new Date().toISOString();await save();console.log(JSON.stringify({output,cost:report.costUsd,failure:report.failure}));}
