import test from'node:test';import assert from'node:assert/strict';
import{needsConditionReview,acceptConditionReview}from'../scripts/condition-review.mjs';
import{jevDecider}from'../scripts/agent-browser-jev.mjs';
const response=choice=>({answers:{conditionApplicability:{type:'choice',choice}}});
const check={kind:'action_check',modelAssessed:true,independentlyVerified:false,immediateAssessment:'ready',verdict:'wrong_target',targetQualification:'mismatch',proposedAction:{op:'click',role:'button',name:'Execute',ref:'@e1'}};
test('same-capture established or not-stated verdict cannot lift a target mismatch',()=>{for(const choice of['established','not_stated']){const r=acceptConditionReview(response(choice),check);assert.equal(r.verdict,'wrong_target');assert.equal(r.conditionReview.overrideWithheld,'contemporaneous_target_mismatch');assert.equal(r.conditionReview.independentlyVerified,false);}});
test('actual navigation and preparation classifications remain available toward missing later prerequisites',()=>{for(const choice of['navigation','preparation']){const r=acceptConditionReview(response(choice),check);assert.equal(r.verdict,choice);assert.equal(r.conditionReview.overrideWithheld,undefined);}});
test('unestablished evidence and mistaken source-page conditions retain original review behavior',()=>{for(const c of[{...check,targetQualification:'unestablished',verdict:'prerequisite_missing'},{...check,targetQualification:undefined,verdict:'prerequisite_missing',conflict:{kind:'effect_before_required_context',requirement:{kind:'detail',phase:'at_effect'}}}])for(const choice of['established','not_stated'])assert.equal(acceptConditionReview(response(choice),c).verdict,'ready');});
test('primary action rejection and opaque control meaning cannot be reopened',()=>{for(const c of[{...check,immediateAssessment:'wrong_target'},{...check,controlMeaning:'unestablished'}]){assert(!needsConditionReview(c));assert.throws(()=>acceptConditionReview(response('established'),c));}});
function fixture(){return{binding:'r',sessionId:'r',stepIndex:0,intent:'Execute the North workspace report only when its existing dates are July1 through September30,2024. Do not change settings.',scope:'Only the requested conditional action',context:'',suppliedValues:{},history:[],observation:{snapshot:'- heading "Workspace report"\n- textbox "Workspace" [readonly, ref=e2]: North\n- textbox "From" [readonly, ref=e3]: July1,2024\n- textbox "To" [readonly, ref=e4]: October31,2024\n- button "Execute" [ref=e1]',refs:{e1:{role:'button',name:'Execute'},e2:{role:'textbox',name:'Workspace',readonly:true,exactValue:'North'},e3:{role:'textbox',name:'From',readonly:true,exactValue:'July1,2024'},e4:{role:'textbox',name:'To',readonly:true,exactValue:'October31,2024'}}},candidates:{c0:{op:'click',role:'button',name:'Execute',ref:'@e1'},handoff:{op:'handoff'}}};}
function decider(condition='established'){const calls=[];const decide=jevDecider({alpha:{decisions:{create:async({decisionsRequest:p})=>{calls.push(p);let answers;if(p.questions.source)answers={source:{type:'choice',choice:'qualified_target'},evidence:{type:'choice',choice:'s1'}};else if(p.questions.actionCheck)answers={actionCheck:{type:'choice',choice:'ready'},targetQualification:{type:'choice',choice:'mismatch'},suggestedNext:{type:'choice',choice:'none'}};else if(p.questions.conditionApplicability)answers=response(condition).answers;else if(p.questions.action)answers={action:{type:'choice',choice:Object.hasOwn(p.questions.action.criteria,'c0')?'c0':'handoff'}};else if(p.questions.nextRoute)answers={nextRoute:{type:'choice',choice:'none'}};else throw Error('Unexpected '+Object.keys(p.questions));return{answers,usage:{cost:.001}}}}}});return{decide,calls};}
async function conflict(d,r){for(let i=0;i<12;i++){const result=await d(r);if(result.interpretations?.[0]?.kind==='condition_conflict')return result;}throw Error('Missing conflict');}
test('real decider retains charge and withholds effect after contradictory condition judgment',async()=>{const r=fixture(),{decide,calls}=decider();await conflict(decide,r);const out=await decide(r);assert.equal(out.choice,undefined);assert.equal(out.assessment,true);assert.equal(out.cost,.001);assert.equal(out.interpretations[0].verdict,'wrong_target');assert.equal(calls.filter(c=>c.questions.conditionApplicability).length,1);});
test('real decider can continue genuine navigation without inventing an at-effect permission',async()=>{const r=fixture(),{decide}=decider('navigation');await conflict(decide,r);const out=await decide(r);assert.equal(out.choice,'c0');assert.equal(out.goalFacts.actionCheck.verdict,'navigation');});
test('pending review still expires with changed observation or removed authority',async()=>{for(const mode of['observation','permission']){const r=fixture(),{decide,calls}=decider();await conflict(decide,r);const changed=structuredClone(r);if(mode==='observation')changed.observation.snapshot+='\n- StaticText "fresh"';else changed.candidates={handoff:{op:'handoff'}};const out=await decide(changed);assert.notEqual(out.choice,'c0');assert.equal(calls.filter(c=>c.questions.conditionApplicability).length,0);}});
