import test from 'node:test';import assert from 'node:assert/strict';import {createExecutionContract} from '../scripts/execution-contract.mjs';
const observation={snapshot:'Complete records A 90 B 70 C 50',objectContext:{objects:[{id:'root',headings:['Records']},...['A','B','C'].map((x,i)=>({id:`o${i}`,role:'article',headings:[x],text:`Measure ${90-i*20}`}))],owners:{e1:'o0',e2:'o1',e3:'o2'}}};
const request={binding:'x',sessionId:'s',stepIndex:0,intent:'Mark the two largest records.',observation,candidates:{c1:{op:'click',ref:'@e1',name:'Mark'},c2:{op:'click',ref:'@e2',name:'Mark'},c3:{op:'click',ref:'@e3',name:'Mark'},step_complete:{op:'step_complete'},handoff:{op:'handoff'}},history:[]};
const response=extra=>({usage:{cost:0.001},answers:Object.fromEntries(Object.entries({collectionMatch:0.9,mode:'ranked',basis:'metric',orderDirection:'unknown',timing:'fixed',scope:'complete',collection:'matched',direction:'max',count:'2',metric_t0:'n0',metric_t1:'n0',metric_t2:'n0',eligible_t0:'yes',eligible_t1:'yes',eligible_t2:'yes',member_t0:'unknown',member_t1:'unknown',member_t2:'unknown',continuity:'preserved',...extra}).map(([id,choice])=>[id,id==='collectionMatch'?{type:'noul',noul:choice}:{type:'choice',choice}]))});
const answer=(id,choice)=>({usage:{cost:0.001},answers:{[id]:{type:'choice',choice},...(id==='operation'?{state:{type:'choice',choice:choice==='already_satisfied'?'satisfied':'absent'}}:{})}});
function bound(extra={},r=request){const t=createExecutionContract(undefined,{allowPagination:extra.scope==='first_segment'}),p=t.prepare(r);assert.ok(p);t.accept(r,p,response(extra));let next=t.prepare(r);if(next?.stage==='scope_identity'){t.accept(r,next,response(extra));next=t.prepare(r);}if(next?.stage==='attributes')t.accept(r,next,response(extra));return t;}
test('original ranked identities control operations after ranking changes',()=>{const t=bound(),r=structuredClone(request);let p=t.prepare(r);assert.deepEqual(Object.keys(p.candidates),['c1']);let d=t.accept(r,p,answer('operation','c1'));assert.equal(d.choice,'c1');r.executedTransitions=[{action:request.candidates.c1,outcome:'tool_succeeded',before:request.observation,after:r.observation}];r.observation.snapshot='A now 10 B 70 C 50';r.observation.objectContext.objects[1].text='Measure 10';p=t.prepare(r);assert.equal(p.stage,'effect');d=t.accept(r,p,answer('effect','satisfied'));assert.equal(d.assessment,true);p=t.prepare(r);assert.deepEqual(p.target.headings,['B']);assert.deepEqual(Object.keys(p.candidates),['c2']);d=t.accept(r,p,answer('operation','already_satisfied'));assert.equal(d.choice,'step_complete');assert.deepEqual(d.executionContract.targets.map(t=>t.status),['satisfied','satisfied']);});
test('uncertain postcondition stops without repeating even after successful tool return',()=>{const t=bound(),r=structuredClone(request);t.accept(r,t.prepare(r),answer('operation','c1'));r.executedTransitions=[{action:r.candidates.c1,before:r.observation,outcome:'tool_succeeded'}];const d=t.accept(r,t.prepare(r),answer('effect','unestablished'));assert.equal(d.choice,'handoff');assert.equal(d.executionContract.targets[0].status,'uncertain');});
test('changed collection, incomplete views, omitted identity text and duplicated targets stop',()=>{for(const mutate of [r=>r.observation.objectContext.objects[0].headings=['Other'],r=>r.observation.limited=true,r=>r.observation.objectContext.objects[1].headingsOmitted=true,r=>r.observation.objectContext.objects[2].headings=['A'],r=>r.observation.objectContext.objects.splice(1,1)]){const t=bound(),r=structuredClone(request);mutate(r);assert.equal(t.prepare(r).stage,'stop');}});
test('only current candidates owned by exact bound object can be selected',()=>{const t=bound(),r=structuredClone(request);delete r.candidates.c1;assert.equal(t.prepare(r).stage,'locate');const p=bound().prepare(request);assert.throws(()=>bound().accept(request,p,answer('operation','c2')));});
test('wrong named collection, unknown coverage, adaptive goals, unrepresented clauses and ties do not establish contract',()=>{for(const extra of [{scope:'unknown'},{timing:'adaptive'},{mode:'other'},{count:'unknown'},{metric_t1:'unknown'}])assert.equal(bound(extra).ledger(),null);const wrong={...request,intent:'Mark the two largest entries in Travel.'};assert.equal(bound({collection:'mismatch'},wrong).ledger(),null);const tie=structuredClone(request);tie.observation.objectContext.objects[3].text='Measure 70';assert.equal(bound({},tie).ledger(),null);});
test('semantic membership preserves already satisfied members as obligations',()=>{const t=bound({mode:'members',direction:'unknown',count:'unknown',member_t0:'yes',member_t1:'no',member_t2:'yes'});assert.deepEqual(t.ledger().targets.map(x=>x.headings),[['A'],['C']]);assert.equal(t.accept(request,t.prepare(request),answer('operation','already_satisfied')).assessment,true);assert.deepEqual(t.prepare(request).target.headings,['C']);});
test('resumed or previously mutated task never rebinds initial rank',()=>{assert.equal(createExecutionContract().prepare({...request,history:[{action:{op:'click'}}]}),null);const t=bound();assert.equal(t.prepare({...request,stepIndex:1,history:[{action:{op:'click'}}]}),null);});
test('missing or mismatched execution readback causes handoff boundary',()=>{const t=bound();t.accept(request,t.prepare(request),answer('operation','c1'));assert.equal(t.prepare(request).stage,'stop');const r={...request,executedTransitions:[{action:request.candidates.c2,before:observation}]};assert.equal(t.prepare(r).stage,'stop');});
test('unknown operation preserves remaining ledger and no early completion',()=>{const t=bound();const d=t.accept(request,t.prepare(request),answer('operation','unknown'));assert.equal(d.choice,'handoff');assert.deepEqual(d.executionContract.targets.map(x=>x.status),['uncertain','pending']);});
test('numeric punctuation is retained and independent metric candidates stay distinct',()=>{const r=structuredClone(request);r.observation.objectContext.objects[1].text='Saves: 6. Comments: 130.';const p=createExecutionContract().prepare(r);assert.deepEqual(p.entries[0].numbers.map(n=>n.value),[6,130]);});
test('unresolved batch permits discovery but cannot fall through to effect or completion',()=>{const t=bound({scope:'unknown'});assert.equal(t.guard(request,{choice:'c1',goalFacts:{actionCheck:{verdict:'ready'}},cost:1}).choice,'handoff');assert.equal(t.guard(request,{choice:'step_complete',cost:1}).choice,'handoff');assert.equal(t.guard(request,{choice:'c1',goalFacts:{actionCheck:{verdict:'navigation'}},cost:1}).choice,'c1');});
test('model-reviewed navigation can precede binding; an unreviewed effect cannot',()=>{const t=bound({scope:'unknown'});t.guard(request,{choice:'c1',goalFacts:{actionCheck:{verdict:'navigation'}}});const r=structuredClone(request);r.history=[{action:r.candidates.c1}];r.executedTransitions=[{action:r.candidates.c1,before:structuredClone(r.observation)}];r.observation.snapshot='new scoped page';assert.equal(t.prepare(r).stage,'interpret');const u=bound({scope:'unknown'});assert.equal(u.prepare(r),null);});
test('effect review contains current target controls and no other object controls',()=>{const r=structuredClone(request);r.observation.refs={e1:{role:'button',name:'Mark'},e2:{role:'button',name:'Mark'},e3:{role:'button',name:'Mark'}};const t=bound({},r);t.accept(r,t.prepare(r),answer('operation','c1'));const after=structuredClone(r);after.observation.refs.e1.name='Unmark';after.executedTransitions=[{action:r.candidates.c1,before:r.observation}];const p=t.prepare(after);assert.deepEqual(p.payload.state.after.controls,{e1:{role:'button',name:'Unmark'}});});
test('paginated all-member contract preserves completed targets and completes only at verified end',()=>{
 const r=structuredClone(request);r.intent='Mark every qualifying record.';r.candidates.next={op:'click',role:'link',name:'Next',ref:'@e9'};r.observation.objectContext.owners.e9='root';r.observation.refs={e9:{role:'link',name:'Next'}};
 const t=bound({mode:'members',scope:'first_segment',collection:'unrestricted',count:'unknown',direction:'unknown',member_t0:'yes',member_t1:'no',member_t2:'no'},r);
 let d=t.accept(r,t.prepare(r),answer('operation','already_satisfied'));assert.equal(d.assessment,true);
 let p=t.prepare(r);assert.equal(p.stage,'advance');d=t.accept(r,p,{usage:{cost:1},answers:{coverage:{type:'choice',choice:'more'},route:{type:'choice',choice:'next'}}});assert.equal(d.choice,'next');
 const next=structuredClone(r);next.observation.snapshot='Page 2';for(const o of next.observation.objectContext.objects.filter(o=>o.id!=='root'))o.headings=[o.headings[0]+' next'];next.executedTransitions=[{action:r.candidates.next,before:r.observation}];next.history=[{action:r.candidates.next}];
 p=t.prepare(next);assert.equal(p.stage,'interpret');assert.equal(p.payload.questions.timing,undefined);assert.equal(p.fixedBindings.timing,'fixed');const a=response({mode:'members',scope:'following_segment',collection:'unrestricted',count:'unknown',direction:'unknown',member_t0:'no',member_t1:'yes',member_t2:'no'});t.accept(next,p,a);t.accept(next,t.prepare(next),a);assert.equal(t.ledger().targets.length,2);assert.deepEqual(t.ledger().targets.map(x=>x.status),['satisfied','pending']);
 d=t.accept(next,t.prepare(next),answer('operation','already_satisfied'));assert.equal(d.assessment,true);p=t.prepare(next);assert.equal(p.stage,'advance');d=t.accept(next,p,{usage:{cost:1},answers:{coverage:{type:'choice',choice:'end'},route:{type:'choice',choice:'unknown'}}});assert.equal(d.choice,'step_complete');assert.equal(d.executionContract.scannedPages,2);
});
test('a later segment cannot start a complete collection traversal',()=>{assert.equal(bound({mode:'members',scope:'following_segment',member_t0:'yes',member_t1:'no',member_t2:'no'}).ledger(),null);});
test('all-member empty set only completes under full collection coverage',()=>{const t=createExecutionContract(),r={...request,intent:'Mark every qualifying record.'},a=response({mode:'members',collection:'unrestricted',member_t0:'no',member_t1:'no',member_t2:'no'});t.accept(r,t.prepare(r),a);assert.equal(t.accept(r,t.prepare(r),a).choice,'step_complete');});
test('explicit observed ranking can bind fixed identities without numeric metrics',()=>{const r=structuredClone(request);for(const [i,o] of r.observation.objectContext.objects.slice(1).entries()){o.text='No numeric metric';o.siblingIndex=i+1;o.parentId='root';}const t=bound({basis:'order',orderDirection:'start',metric_t0:'unknown',metric_t1:'unknown',metric_t2:'unknown'},r);assert.deepEqual(t.ledger().targets.map(x=>x.headings),[['A'],['B']]);r.observation.objectContext.objects[1].siblingIndex=3;r.observation.objectContext.objects[3].siblingIndex=1;assert.deepEqual(t.prepare(r).target.headings,['A']);});
test('displayed ordering cannot mix unrelated containers or duplicate ordinals',()=>{for(const change of [r=>r.observation.objectContext.objects[2].parentId='other',r=>r.observation.objectContext.objects[2].siblingIndex=1]){const r=structuredClone(request);for(const [i,o] of r.observation.objectContext.objects.slice(1).entries()){o.siblingIndex=i+1;o.parentId='root';}change(r);assert.equal(bound({basis:'order',orderDirection:'start'},r).ledger(),null);}});
test('continuation preserves initial target identities after successful dispatch and changed rank',()=>{const t=bound();t.accept(request,t.prepare(request),answer('operation','c1'));const saved=JSON.parse(JSON.stringify(t.checkpoint())),u=createExecutionContract(saved),r=structuredClone(request);r.history=[{stepIndex:0,action:r.candidates.c1,outcome:'tool_succeeded'}];r.observation.snapshot='A score now below C';r.observation.objectContext.objects[1].text='Measure 1';r.executedTransitions=[];let p=u.prepare(r);assert.equal(p.stage,'effect');u.accept(r,p,answer('effect','satisfied'));p=u.prepare(r);assert.deepEqual(p.target.headings,['B']);assert.equal(saved.plan.targets[0].status,'dispatched');});
test('an action-budget return before dispatch resumes a pending target without claiming an effect',()=>{const t=bound();t.accept(request,t.prepare(request),answer('operation','c1'));const u=createExecutionContract(t.checkpoint());assert.equal(u.prepare(request).stage,'operate');assert.equal(u.ledger().targets[0].status,'pending');});
test('uncertain effects and changed caller context cannot resume by silently rebinding',()=>{const t=bound();t.accept(request,t.prepare(request),answer('operation','unknown'));const u=createExecutionContract(t.checkpoint());assert.equal(u.prepare(request).stage,'stop');const v=createExecutionContract(bound().checkpoint());assert.equal(v.prepare({...request,context:'Different scope'}).stage,'stop');});
test('invalid continuation schema is rejected without model or browser activity',()=>{assert.throws(()=>createExecutionContract({schema:99}));});

test('grouped numbers stay whole and unsupported decimal separators do not produce partial metrics',()=>{
 const r=structuredClone(request);r.observation.objectContext.objects[1].text='Saves: 10,041. Measure -2,001.25. Unsupported 1,25 or 1.234,5.';
 const p=createExecutionContract().prepare(r);assert.deepEqual(p.entries[0].numbers.map(n=>[n.literal,n.value]),[['10,041',10041],['-2,001.25',-2001.25]]);
});

test('collection meaning is model-assessed rather than requiring a literal root heading in the caller goal',()=>{
 const r=structuredClone(request);r.intent='Mark the two largest records in the requested archive.';r.observation.objectContext.objects[0].headings=['/collections/Records'];
 assert.equal(bound({collection:'matched'},r).ledger().targets.length,2);
 assert.equal(bound({collection:'mismatch'},r).ledger(),null);assert.equal(bound({collection:'unknown'},r).ledger(),null);
});

test('next-page binding uncertainty stops before a fallback can skip unprocessed members',()=>{
 const r=structuredClone(request);r.intent='Mark every qualifying record.';r.candidates.next={op:'click',role:'link',name:'Next',ref:'@e9'};r.observation.objectContext.owners.e9='root';
 const t=bound({mode:'members',scope:'first_segment',collection:'unrestricted',member_t0:'no',member_t1:'no',member_t2:'no'},r);
 t.accept(r,t.prepare(r),{answers:{coverage:{type:'choice',choice:'more'},route:{type:'choice',choice:'next'}}});
 const next=structuredClone(r);next.observation.snapshot='next';next.observation.objectContext.objects.slice(1).forEach(o=>o.headings=[o.headings[0]+' next']);next.executedTransitions=[{action:r.candidates.next,before:r.observation}];next.history=[{action:r.candidates.next}];
 const p=t.prepare(next);assert.deepEqual(Object.keys(p.payload.questions),['continuity']);const d=t.accept(next,p,response({continuity:'unknown'}));assert.equal(d.choice,'handoff');assert.match(d.executionContract.stopReason,/do not skip/);
});

test('per-object membership does not receive earlier scope or continuity verdicts as evidence',()=>{
 const t=createExecutionContract(),p=t.prepare(request);t.accept(request,p,response({mode:'members',member_t0:'yes',member_t1:'no',member_t2:'no'}));const a=t.prepare(request);assert.equal(a.stage,'attributes');assert.deepEqual(Object.keys(a.payload.state),['callerGoal','collectionLabels','items']);assert.equal(JSON.stringify(a.payload).includes('selectionRule'),false);
});

test('default controller declines multi-page member specialization before any effect',()=>{
 const t=createExecutionContract(),p=t.prepare(request);const d=t.accept(request,p,response({mode:'members',scope:'first_segment',collection:'matched'}));assert.equal(d.useGeneralController,true);assert.equal(t.ledger(),null);assert.equal(t.prepare(request),null);
});
test('a saved experimental paginated contract cannot dispatch under the default policy',()=>{
 const t=bound({mode:'members',scope:'first_segment',member_t0:'yes',member_t1:'no',member_t2:'no'});const resumed=createExecutionContract(t.checkpoint());assert.equal(resumed.prepare(request).stage,'stop');assert.match(resumed.prepare(request).reason,/not enabled/);
});

test('eligibility is applied before ranking without changing target lifetime',()=>{
 const t=bound({eligible_t1:'no'});assert.deepEqual(t.ledger().targets.map(x=>x.headings),[['A'],['C']]);
 t.accept(request,t.prepare(request),answer('operation','c1'));const r=structuredClone(request);r.observation.snapshot='after score change';r.observation.objectContext.objects[1].text='Measure 1';r.history=[{action:r.candidates.c1,outcome:'tool_succeeded'}];r.executedTransitions=[{action:r.candidates.c1,outcome:'tool_succeeded',before:request.observation,after:r.observation}];
 t.accept(r,t.prepare(r),answer('effect','satisfied'));assert.deepEqual(t.prepare(r).target.headings,['C']);
});
test('excluded objects need no numeric metric and cannot create a rank boundary tie',()=>{
 assert.deepEqual(bound({eligible_t1:'no',metric_t1:'unknown'}).ledger().targets.map(x=>x.headings),[['A'],['C']]);
 const r=structuredClone(request);r.observation.objectContext.objects[2].text='Measure 90';assert.deepEqual(bound({count:'1',eligible_t1:'no'},r).ledger().targets.map(x=>x.headings),[['A']]);
});
test('unknown eligibility and too few eligible objects bind no targets or effects',()=>{
 for(const extra of [{eligible_t1:'unknown'},{eligible_t1:'no',eligible_t2:'no'}])assert.equal(bound(extra).ledger(),null);
});
test('displayed ranking filters eligible entries before applying requested count',()=>{
 const r=structuredClone(request);for(const [i,o] of r.observation.objectContext.objects.slice(1).entries()){o.siblingIndex=i+1;o.parentId='root';}
 assert.deepEqual(bound({basis:'order',orderDirection:'start',eligible_t1:'no'},r).ledger().targets.map(x=>x.headings),[['A'],['C']]);
});
test('ranked eligibility and metric judgments share evidence but not earlier answers',()=>{
 const t=createExecutionContract(),p=t.prepare(request);t.accept(request,p,response());t.accept(request,t.prepare(request),response());const a=t.prepare(request);
 assert.equal(a.payload.questions.eligible_t0.type,'choice');assert.equal(a.payload.questions.metric_t0.type,'choice');assert.deepEqual(Object.keys(a.payload.state),['callerGoal','collectionLabels','items']);
});

test('a contrary base collection judgment cannot establish ranked targets',()=>{assert.equal(bound({collectionMatch:0.1}).ledger(),null);assert.equal(bound({collectionMatch:0.5}).ledger(),null);});

test('collection identity uses only the caller goal and observed labels',()=>{const t=createExecutionContract();t.accept(request,t.prepare(request),response());const p=t.prepare(request);assert.equal(p.stage,'scope_identity');assert.equal(p.payload.questions.collectionMatch.type,'noul');assert.deepEqual(Object.keys(p.payload.state),['intent','observedCollectionLabels']);assert.equal(JSON.stringify(p.payload).includes('selectionRule'),false);});
