import test from 'node:test';import assert from 'node:assert/strict';
import{jevDecider}from'../scripts/agent-browser-jev.mjs';
import{createNumericLedger}from'../scripts/numeric-ledger.mjs';
import{groundedValueAction,valueBindingRequest,acceptValueBinding,valueBindingFrame}from'../scripts/value-binding.mjs';
function request(count=1){const refs={e1:{role:'textbox',name:'Record code',readonly:true,inputType:'text',exactValue:'L81'}},candidates={},lines=['- heading "Cove record"','- textbox "Record code" [readonly, ref=e1]: L81'];for(let i=0;i<count;i++){const ref='e'+(i+2),name=i?'Charge '+i:'Charge';refs[ref]={role:'textbox',name,inputType:'text',exactValue:'25.00'};candidates['f'+i]={op:'request_input',ref:'@'+ref,role:'textbox',name};lines.push(`- textbox ${JSON.stringify(name)} [ref=${ref}]: 25.00`);}return{binding:'r',sessionId:'r',stepIndex:0,intent:'Increase Charge on Cove by 12%. Leave all other fields unchanged.',scope:'Only requested edits',context:'',suppliedValues:{},history:[],numericLedger:createNumericLedger().snapshot(),observation:{snapshot:lines.join('\n'),refs},candidates:{...candidates,handoff:{op:'handoff'}}};}
function model(handler=()=>({valueSource:{type:'choice',choice:'unknown'}})){const payloads=[];return{payloads,api:{alpha:{decisions:{create:async({decisionsRequest:p})=>{payloads.push(p);let answers;if(p.questions.source)answers={source:{type:'choice',choice:'unconstrained'},evidence:{type:'choice',choice:'unknown'},phase:{type:'choice',choice:'none'}};else if(p.questions.valueSource||p.questions.numericField)answers=handler(p);else if(p.questions.action)answers={action:{type:'choice',choice:'handoff'}};else if(p.questions.nextRoute)answers={nextRoute:{type:'choice',choice:'none'}};else throw Error('Unexpected '+Object.keys(p.questions));return{answers,usage:{cost:.001}}}}}}};}
const choice=choices=>Object.fromEntries(Object.entries(choices).map(([k,v])=>[k,{type:'choice',choice:v}]));
function correct(p){const anchor=Object.entries(p.state.numericIdentityEvidence.anchors).find(([,a])=>a.kind==='readonly')[0];const targets=Object.keys(p.questions.numericTarget.criteria).filter(k=>!['new_target','unknown'].includes(k));return choice({valueSource:'derived:0:percent_add',numericIdentity:anchor,numericTarget:targets[0]??'new_target'});}
async function untilAction(d,r,m){const results=[];for(let i=0;i<25;i++){results.push(await d(r));if(m.payloads.at(-1)?.questions.action)return results;}throw Error('Action ranking never resumed');}
function committed(r,status='tool_succeeded'){const ledger=createNumericLedger(),f=r.candidates.f0,p=valueBindingRequest(r,f),s=acceptValueBinding({answers:correct(p)},r,f,p),binding={...s,ref:f.ref,frame:valueBindingFrame(r.observation)},a=groundedValueAction(r,r.candidates,binding),id=ledger.dispatch(a,r);assert(id);ledger.settle(id,status,status==='tool_succeeded'?a.value:undefined);return ledger;}
test('review: speculative probes stop at six fields and never consume ledger',async()=>{const r=request(9),m=model(),d=jevDecider(m.api),out=await untilAction(d,r,m);assert.equal(m.payloads.filter(p=>p.questions.valueSource).length,6);assert.equal(out.filter(x=>x.interpretations?.[0]?.kind==='numeric_value_probe_proposal').length,6);assert(out.every(x=>x.valueBinding===undefined));assert.deepEqual(r.numericLedger.entries,[]);});
test('review: observation/ref churn cannot exceed six speculative probes in the same step',async()=>{const m=model(),d=jevDecider(m.api);await d(request());for(let i=0;i<6;i++){const r=request();r.observation.snapshot+='\n- StaticText "capture '+i+'"';const proposed=await d(r);assert.equal(proposed.interpretations?.[0]?.kind,'numeric_value_probe_proposal');await d(r);}const r=request();r.observation.snapshot+='\n- StaticText "seventh"';await d(r);assert.equal(m.payloads.filter(p=>p.questions.valueSource).length,6);assert(m.payloads.at(-1).questions.action);});
test('review: unknown source on unchanged capture is asked once and does not force input boundary',async()=>{const r=request(),m=model(),d=jevDecider(m.api),out=await untilAction(d,r,m);assert.equal(m.payloads.filter(p=>p.questions.valueSource).length,1);assert(!out.some(x=>x.interpretations?.some(v=>v.kind==='input_boundary_review_proposal')));assert(!out.some(x=>x.choice&&x.choice!=='handoff'));});
test('review: excluded unauthorized field and already offered fill receive no speculative binding',async()=>{for(const mode of['denied','offered']){const r=request();if(mode==='denied')delete r.candidates.f0;else r.candidates.bound={...r.candidates.f0,op:'fill',value:'28.00'};const m=model(),d=jevDecider(m.api);await d(r);await d(r);assert.equal(m.payloads.filter(p=>p.questions.valueSource).length,0);}});
test('review: pending initial probe invalidates before paid judgment on changed scope/context/identity/role/source or candidates',async()=>{for(const mode of['scope','context','identity','type','source','candidate']){const r=request(),m=model(correct),d=jevDecider(m.api);await d(r);await d(r);const n=structuredClone(r);if(['scope','context'].includes(mode))n[mode]+=' changed';if(mode==='identity')n.observation.refs.e1.exactValue='L82';if(mode==='type')n.observation.refs.e2.inputType='password';if(mode==='source')n.observation.refs.e2.exactValue='n/a';if(mode==='candidate')n.candidates={handoff:{op:'handoff'}};const answer=await d(n);assert.equal(m.payloads.filter(p=>p.questions.valueSource).length,0,mode);assert.equal(answer.valueBinding,undefined,mode);}});
test('review: prepared and uncertain writes remain blocked despite proactive calculation and ref churn',async()=>{for(const status of['tool_succeeded','unknown']){const r=request(),ledger=committed(r,status),saved=structuredClone(ledger.snapshot());r.numericLedger=saved;r.observation.refs.e2.exactValue=status==='tool_succeeded'?'28.00':'25.00';r.observation.snapshot=r.observation.snapshot.replace('25.00',r.observation.refs.e2.exactValue);const m=model(correct),d=jevDecider(m.api),out=await untilAction(d,r,m);assert(out.every(a=>!a.valueBinding));assert.deepEqual(r.numericLedger,saved);}});
test('review: successful advisory proposal computes original source exactly but does not dispatch or reserve duplicate protection',async()=>{const r=request(),m=model(correct),d=jevDecider(m.api);await d(r);await d(r);const out=await d(r),a=groundedValueAction(r,r.candidates,out.valueBinding);assert.equal(a.value,'28.00');assert.equal(out.choice,undefined);assert.deepEqual(r.numericLedger.entries,[]);const stale=structuredClone(r);stale.observation.refs.e2.exactValue='26.00';assert.equal(groundedValueAction(stale,stale.candidates,out.valueBinding),null);});
test('review: forged unsupported arithmetic selection fails without binding or ledger consumption',async()=>{const r=request(),m=model(p=>({...correct(p),valueSource:{type:'choice',choice:'derived:999:percent_add'}})),d=jevDecider(m.api);await d(r);await d(r);await assert.rejects(d(r),/Invalid value binding/);assert.deepEqual(r.numericLedger.entries,[]);});
test('review: conditional same-record field proof cannot survive changed ledger or witness',async()=>{for(const mode of['ledger','witness']){const r=request(),ledger=committed(r);r.numericLedger=ledger.snapshot();r.intent='Increase Charge and Allowance on Cove by 12%.';r.candidates.f0.name='Allowance';r.observation.refs.e2.name='Allowance';r.observation.refs.e2.exactValue='30.00';r.observation.snapshot=r.observation.snapshot.replace('Charge','Allowance').replace('25.00','30.00');const m=model(p=>p.questions.numericField?choice({numericField:'new_field'}):correct(p)),d=jevDecider(m.api);await d(r);await d(r);const staged=await d(r);assert.equal(staged.interpretations?.[0]?.kind,'value_binding_proposal');const n=structuredClone(r);if(mode==='ledger')n.numericLedger.revision++;else n.crossViewWitness={unexpected:true};const answer=await d(n);assert.equal(answer.valueBinding,undefined);assert.equal(answer.interpretations?.[0]?.kind,'numeric_value_probe');assert.deepEqual(r.numericLedger,ledger.snapshot());}});
